p8105_hw2_lt2949
================
2023-10-01

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(dplyr)
```

# Problem1

Clean the data in `pols-month.csv` and replace the month number with
month name.

``` r
#Clean the data in 'pols-month.csv'
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -starts_with("prez"))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_num)`

Clean the data in `snp.csv` with similar method.

``` r
# Clean the data in 'snp.csv'
snp = 
  read_csv("./fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  arrange(year, month) |>
  mutate(month = month.name[month]) |>
  select(year, month, close) 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

We tidy the `unemployment` data so that it can be merged with the `pols`
and `snp` datasets.

``` r
# Clean the data in 'umemployment.csv'
unemployment = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

Merge the three datasets.

``` r
data_538 = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
str(data_538)
```

    ## tibble [822 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ year        : num [1:822] 1947 1947 1947 1947 1947 ...
    ##  $ month       : chr [1:822] "January" "February" "March" "April" ...
    ##  $ month_num   : int [1:822] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ gov_gop     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : num [1:822] 51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : num [1:822] 253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : num [1:822] 23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : num [1:822] 45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : num [1:822] 198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr [1:822] "dem" "dem" "dem" "dem" ...
    ##  $ month_abb   : chr [1:822] "Jan" "Feb" "Mar" "Apr" ...
    ##  $ close       : num [1:822] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num [1:822] NA NA NA NA NA NA NA NA NA NA ...

The merged dataset is derived from the three previously sets, unified
using ‘year’ and ‘month’ as criteria. Covering a spectrum of political,
economic, and unemployment metrics, its coverage extends from 1947
through 2015. The `combined_data` set holds 822 records across 11
distinct columns. Key variables present in this set are: `year`,
`month`, `gov_gop`, `sen_gop`, `rep_gop`, `gov_dem`, `sen_dem`,
`rep_dem`, `president`, `close`, and `unemployment_rate`.

# Problem2

``` r
# Import and clean Mr.Trash Wheel data
mr_trash_wheel <- 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N586") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster))|>
  mutate(homes_powered = (weight_tons * 500) %/% 30)

# Import and clean Professor Trash Wheel data
prof_trash_wheel <- 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M108") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster))|>
  mutate(homes_powered = (weight_tons * 500) %/% 30)

# Import and clean Gwynnda Trash Wheel data
gwy_trash_wheel <- 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:L157") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster))|>
  mutate(homes_powered = (weight_tons * 500) %/% 30)

# Add a new variable 
mr_trash_wheel <- mr_trash_wheel %>% mutate(wheel_name = "Mr. Trash Wheel")

prof_trash_wheel <- prof_trash_wheel %>% mutate(wheel_name = "Professor Trash Wheel")

gwy_trash_wheel <- gwy_trash_wheel %>% mutate(wheel_name = "Gwynnda Trash Wheel")

# Convert "year" to numeric
mr_trash_wheel$year <- as.numeric(mr_trash_wheel$year)
prof_trash_wheel$year <- as.numeric(prof_trash_wheel$year)
gwy_trash_wheel$year <- as.numeric(gwy_trash_wheel$year)

# Combine all datasets
trash_wheel_collection <- bind_rows(mr_trash_wheel, prof_trash_wheel, gwy_trash_wheel)
str(trash_wheel_collection)
```

    ## tibble [845 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ dumpster          : num [1:845] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:845] "May" "May" "May" "May" ...
    ##  $ year              : num [1:845] 2014 2014 2014 2014 2014 ...
    ##  $ date              : POSIXct[1:845], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons       : num [1:845] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:845] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : num [1:845] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:845] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:845] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:845] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ plastic_bags      : num [1:845] 584 496 1080 896 368 ...
    ##  $ wrappers          : num [1:845] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : num [1:845] 7.2 5.2 6 6 7.2 5.2 3.2 6.4 5.6 7.2 ...
    ##  $ homes_powered     : num [1:845] 71 45 57 51 67 45 31 61 42 62 ...
    ##  $ wheel_name        : chr [1:845] "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" ...

The `trash_wheel_collection` dataset combines three separate datasets:
`mr_trash_wheel`, `prof_trash_wheel`, and `gwy_trash_wheel`. It consists
of 845 observations and 15 variables. Within the
`trash_wheel_collection` dataset, there are variables detailing
collection dates (i.e., `date`), a variable representing the total
weight of the trash (i.e., `weight_tons`), variables denoting different
types of trash (e.g., `plastic_bags`), and a derived data variable
(i.e., `homes_powered`). According to the available data, Professor
Trash Wheel collected a total weight of 216.26 tons of trash.
Additionally, in July 2021, Gwynnda collected 1.63^{4} cigarette butts.

# Problem3

``` r
# Import and clean the baseline
baseline <- 
  read.csv("data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(
      #Convert "sex" and "apoe4" to non-numeric
      sex = recode(sex, "1" = "male", "0" = "female"),
      apoe4 = recode(apoe4, "1" = "carrier", "0" = "non-carrier")
  ) |>
  rename("study_id" = "id")
  
# Remove participants who do not meet the stated inclusion criteria 
baseline_meet <- filter(baseline, is.na(age_at_onset) | age_at_onset == "." | current_age < age_at_onset)

# Filter the number of participants who developed MCI
mci_developed <- filter(baseline_meet, !is.na(age_at_onset) & age_at_onset != ".")

# Statistics process
women_apoe4_carriers <- sum(baseline$sex == "female" & baseline$apoe4 == "carrier")
total_women <- sum(baseline$sex == "female")
prop_women_carriers <- round((women_apoe4_carriers / total_women)*100, digits = 2)
```

After importing the data, we convert the variables `sex` and `apoe4` to
more meaningful expressions. In the original baseline dataset, there are
483 observations. However, out of these, only 479 participants met the
specified requirements, as indicated by the number of observations in
the `baseline_meet` dataset. Furthermore, 93 participants developed MCI.
The average baseline age of the participants is 65.03. In the study, the
proportion of women who are carriers stands at 29.86%.

``` r
# Import and clean the longitudinally observed biomarker values dataset
amyloid <- 
  read.csv("data_mci/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names()

# Combine datasets
combined_mci <- merge(baseline_meet, amyloid, by = "study_id")

# Check participants in only one of the datasets
only_baseline <- setdiff(baseline_meet$study_id, amyloid$study_id)
only_amyloid <- setdiff(amyloid$study_id, baseline_meet$study_id)

# Exporting the combined_mci to a CSV file
write.csv(combined_mci, "data_mci/combined_mci.csv", row.names = FALSE)
```

There are 8 participants only in baseline dataset, and there are 16
participants only in amyloid dataset. The combined dataset has 471
observations and 11 variables.
